export const PLAYER = {
    SPEED: 2,
    GROUND_POSITION: 356,
    JUMP_STRENGTH: 6,
    MAX_Y_VELOCITY: 10,
    GRAVITY: 0.5
}

export const KICK = {
    KICK_DURATION: 150,
    FOOT_ANGLE_START: -90,
    FOOT_ANGLE_END: -195,
    LEG_LENGTH: 20,
    START: Math.PI,
    END: -0.5,
    START_OFFSET: 0.3
}

export const PARTICLES = {
    MAX_PARTICLES: 15,
    PARTICLE_SPAWN_RATE: 4
}

export const BALL = {
    RADIUS: 20,
    GRAVITY: 0.4,
    BOUNCE: 0.7,
    FRICTION: 0.98,
    GROUND_FRICTION: 0.95,
    MAX_VELOCITY: 12,
    KICK_POWER_MIN: 3,
    KICK_POWER_MAX: 10,
    GROUND_POSITION: 397,
}

export const COLLISION = {
    PLAYER_R: 22,
    FOOT_R: 10,
    RESTITUTION: 0.6,
    FOOT_RESTITUTION: 0.75,
    MAX_STEP_FRAC: 1.8,
}



